spring:
    redis:
        host: localhost
        password: redis
        port: 6379
        pool:
            max-idle: 100
            min-idle: 1
            max-active: 1000
            max-wait: -1